export SUPABASE_URL="https://kjkztapkteomazarxnzc.supabase.co"
export SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtqa3p0YXBrdGVvbWF6YXJ4bnpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyNzg3MDksImV4cCI6MjA4NDg1NDcwOX0.-9YmCM4D3QfxdxcnGvZqKJfMeNdAcnrwvsuLan150kA"
